---
# Source: tidb-docker-compose/templates/docker-compose.yml

services:
  pd0:
    image: pingcap/pd:latest
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - ./config/pd.toml:/pd.toml:ro
      - ./data:/data
      - ./logs:/logs
    command:
      - --name=pd0
      - --client-urls=http://0.0.0.0:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://10.0.0.96:2379
      - --advertise-peer-urls=http://10.0.0.96:2380
      - --initial-cluster=pd0=http://10.0.0.96:2380,pd1=http://10.0.0.96:2480,pd2=http://10.0.0.96:2580
      - --data-dir=/data/pd0
      - --config=/pd.toml
      - --log-file=/logs/pd0.log
    # sysctls:
    #   net.core.somaxconn: 32768
    # ulimits:
    #   nofile:
    #     soft: 1000000
    #     hard: 1000000
    restart: on-failure
  
  pd1:
    image: pingcap/pd:latest
    ports:
      - "2479:2479"
      - "2480:2480"
    volumes:
      - ./config/pd.toml:/pd.toml:ro
      - ./data:/data
      - ./logs:/logs
    command:
      - --name=pd1
      - --client-urls=http://0.0.0.0:2479
      - --peer-urls=http://0.0.0.0:2480
      - --advertise-client-urls=http://10.0.0.96:2479
      - --advertise-peer-urls=http://10.0.0.96:2480
      - --initial-cluster=pd0=http://10.0.0.96:2380,pd1=http://10.0.0.96:2480,pd2=http://10.0.0.96:2580
      - --data-dir=/data/pd1
      - --config=/pd.toml
      - --log-file=/logs/pd1.log
    # sysctls:
    #   net.core.somaxconn: 32768
    # ulimits:
    #   nofile:
    #     soft: 1000000
    #     hard: 1000000
    restart: on-failure
  
  pd2:
    image: pingcap/pd:latest
    ports:
      - "2579:2579"
      - "2580:2580"
    volumes:
      - ./config/pd.toml:/pd.toml:ro
      - ./data:/data
      - ./logs:/logs
    command:
      - --name=pd2
      - --client-urls=http://0.0.0.0:2579
      - --peer-urls=http://0.0.0.0:2580
      - --advertise-client-urls=http://10.0.0.96:2579
      - --advertise-peer-urls=http://10.0.0.96:2580
      - --initial-cluster=pd0=http://10.0.0.96:2380,pd1=http://10.0.0.96:2480,pd2=http://10.0.0.96:2580
      - --data-dir=/data/pd2
      - --config=/pd.toml
      - --log-file=/logs/pd2.log
    # sysctls:
    #   net.core.somaxconn: 32768
    # ulimits:
    #   nofile:
    #     soft: 1000000
    #     hard: 1000000
    restart: on-failure
  
  tikv0:
    image: pingcap/tikv:latest
    ports:
      - "20160:20160"
    volumes:
      - ./config/tikv.toml:/tikv.toml:ro
      - ./data:/data
      - ./logs:/logs
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=10.0.0.96:20160
      - --data-dir=/data/tikv0
      - --pd=10.0.0.96:2379,10.0.0.96:2479,10.0.0.96:2579
      - --config=/tikv.toml
      - --log-file=/logs/tikv0.log
    depends_on:
      - "pd0"
      - "pd1"
      - "pd2"
    # sysctls:
    #   net.core.somaxconn: 32768
    # ulimits:
    #   nofile:
    #     soft: 1000000
    #     hard: 1000000
    restart: on-failure
  
  tikv1:
    image: pingcap/tikv:latest
    ports:
      - "20161:20161"
    volumes:
      - ./config/tikv.toml:/tikv.toml:ro
      - ./data:/data
      - ./logs:/logs
    command:
      - --addr=0.0.0.0:20161
      - --advertise-addr=10.0.0.96:20161
      - --data-dir=/data/tikv1
      - --pd=10.0.0.96:2379,10.0.0.96:2479,10.0.0.96:2579
      - --config=/tikv.toml
      - --log-file=/logs/tikv1.log
    depends_on:
      - "pd0"
      - "pd1"
      - "pd2"
    # sysctls:
    #   net.core.somaxconn: 32768
    # ulimits:
    #   nofile:
    #     soft: 1000000
    #     hard: 1000000
    restart: on-failure
  
  tikv2:
    image: pingcap/tikv:latest
    ports:
      - "20162:20162"    
    volumes:
      - ./config/tikv.toml:/tikv.toml:ro
      - ./data:/data
      - ./logs:/logs
    command:
      - --addr=0.0.0.0:20162
      - --advertise-addr=10.0.0.96:20162
      - --data-dir=/data/tikv2
      - --pd=10.0.0.96:2379,10.0.0.96:2479,10.0.0.96:2579
      - --config=/tikv.toml
      - --log-file=/logs/tikv2.log
    depends_on:
      - "pd0"
      - "pd1"
      - "pd2"
    # sysctls:
    #   net.core.somaxconn: 32768
    # ulimits:
    #   nofile:
    #     soft: 1000000
    #     hard: 1000000
    restart: on-failure
  
  
  tidb0:
    image: pingcap/tidb:latest
    ports:
      - "4000:4000"
      - "10080:10080"
    volumes:
      - ./config/tidb.toml:/tidb.toml:ro
      - ./logs:/logs
    command:
      - --store=tikv
      - -P
      - "4000"
      - --path=10.0.0.96:2379,10.0.0.96:2479,10.0.0.96:2579
      - --config=/tidb.toml
      - --log-file=/logs/tidb.log
      - --advertise-address=10.0.0.96
    depends_on:
      - "tikv0"
      - "tikv1"
      - "tikv2"
    restart: on-failure
  tidb1:
    image: pingcap/tidb:latest
    ports:
      - "4001:4001"
      - "10081:10081"
    volumes:
      - ./config/tidb.toml:/tidb.toml:ro
      - ./logs:/logs
    command:
      - --store=tikv
      - -P
      - "4001"
      - --path=10.0.0.96:2379,10.0.0.96:2479,10.0.0.96:2579
      - --config=/tidb.toml
      - --log-file=/logs/tidb.log
      - --advertise-address=10.0.0.96
    depends_on:
      - "tikv0"
      - "tikv1"
      - "tikv2"
    restart: on-failure  
  tidb2:
    image: pingcap/tidb:latest
    ports:
      - "4002:4002"
      - "10082:10082"
    volumes:
      - ./config/tidb.toml:/tidb.toml:ro
      - ./logs:/logs
    command:
      - --store=tikv
      - -P
      - "4002"
      - --path=10.0.0.96:2379,10.0.0.96:2479,10.0.0.96:2579
      - --config=/tidb.toml
      - --log-file=/logs/tidb.log
      - --advertise-address=10.0.0.96
    depends_on:
      - "tikv0"
      - "tikv1"
      - "tikv2"
    restart: on-failure
  tidb-vision:
    image: pingcap/tidb-vision:latest
    environment:
      PD_ENDPOINT: 10.0.0.96:2379
    ports:
      - "8010:8010"
    restart: on-failure

  # prometheus:
  #   user: root
  #   image: prom/prometheus:latest
  #   command:
  #     - --log.level=error
  #     - --storage.tsdb.path=/data/prometheus
  #     - --config.file=/etc/prometheus/prometheus.yml
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  #     - ./config/pd.rules.yml:/etc/prometheus/pd.rules.yml:ro
  #     - ./config/tikv.rules.yml:/etc/prometheus/tikv.rules.yml:ro
  #     - ./config/tidb.rules.yml:/etc/prometheus/tidb.rules.yml:ro
  #     - ./data:/data
  #   restart: on-failure
  # grafana:
  #   image: grafana/grafana:latest
  #   user: "0"
  #   environment:
  #     GF_LOG_LEVEL: error
  #     GF_PATHS_PROVISIONING: /etc/grafana/provisioning
  #     GF_PATHS_CONFIG: /etc/grafana/grafana.ini
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./config/grafana:/etc/grafana
  #     - ./config/dashboards:/tmp/dashboards
  #     - ./data/grafana:/var/lib/grafana
  #   restart: on-failure
  # dashboard-installer:
  #   image: pingcap/tidb-dashboard-installer:v2.0.0
  #   command: ["grafana:3000"]
  #   restart: on-failure
