CREATE SCHEMA IF NOT EXISTS `ifn-boulder`;

USE `ifn-boulder`;

--
-- fqdnSets
CREATE TABLE IF NOT EXISTS `fqdnSets` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `setHash` binary(32) NOT NULL,
  `serial` varchar(255) NOT NULL,
  `issued` datetime NOT NULL,
  `expires` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `setHash_issued_idx` (`setHash`,`issued`),
  KEY `serial` (`serial`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8
 PARTITION BY RANGE (`id`)
(PARTITION `p_1` VALUES LESS THAN (100),
 PARTITION `p_2` VALUES LESS THAN (200),
 PARTITION `p_3` VALUES LESS THAN (300),
 PARTITION `p_4` VALUES LESS THAN (400),
 PARTITION `p_5` VALUES LESS THAN (500),
 PARTITION `p_6` VALUES LESS THAN (600),
 PARTITION `p_7` VALUES LESS THAN (700),
 PARTITION `p_10` VALUES LESS THAN (1000),
 PARTITION `p_50` VALUES LESS THAN (5000),
 PARTITION `p_150` VALUES LESS THAN (15000),
 PARTITION `p_250` VALUES LESS THAN (25000),
 PARTITION `p_end` VALUES LESS THAN MAXVALUE);

--
-- orderFqdnSets
CREATE TABLE IF NOT EXISTS `orderFqdnSets` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `setHash` binary(32) NOT NULL,
  `orderID` bigint(20) NOT NULL,
  `registrationID` bigint(20) NOT NULL,
  `expires` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `setHash_expires_idx` (`setHash`,`expires`),
  KEY `orderID_idx` (`orderID`),
  KEY `orderFqdnSets_registrationID_registrations` (`registrationID`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8
 PARTITION BY RANGE (`id`)
(PARTITION `p_1` VALUES LESS THAN (100),
 PARTITION `p_2` VALUES LESS THAN (200),
 PARTITION `p_3` VALUES LESS THAN (300),
 PARTITION `p_4` VALUES LESS THAN (400),
 PARTITION `p_5` VALUES LESS THAN (500),
 PARTITION `p_6` VALUES LESS THAN (600),
 PARTITION `p_7` VALUES LESS THAN (700),
 PARTITION `p_10` VALUES LESS THAN (1000),
 PARTITION `p_50` VALUES LESS THAN (5000),
 PARTITION `p_150` VALUES LESS THAN (15000),
 PARTITION `p_250` VALUES LESS THAN (25000),
 PARTITION `p_end` VALUES LESS THAN MAXVALUE);

